    # Publish all joint states -----------------------------------
    joints_update:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    # Position Controllers ---------------------------------------
    joint1_position_controller_1:
      type: position_controllers/JointPositionController
      joint: Joint_1
      pid: {p: 1300.0, i: 0.0, d: 5, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}
      
    # Velocity Controllers ---------------------------------------
    joint1_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: Joint_1
      pid: {p: 100.0, i: 100.0, d: 0.0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}
      
    # Joint-Trajectory Controller
    trajectory_arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - Joint_1
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
        - Joint_6
      gains:
       Joint_1:
         p: 100
         d: 1
         i: 1
         i_clamp: 1
       Joint_2:
         p: 100
         d: 1
         i: 1
         i_clamp: 1
       Joint_3:
         p: 100
         d: 1
         i: 1
         i_clamp: 1
       Joint_4:
         p: 100
         d: 1
         i: 1
         i_clamp: 1
       Joint_5:
         p: 100
         d: 1
         i: 1
         i_clamp: 1
       Joint_6:
         p: 100
         d: 1
         i: 1
         i_clamp: 1
