controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - Joint_6
      - Gripper_L_1
      - Gripper_L_3
      - Gripper_L_2
      - Gripper_R_1
      - Gripper_R_3
      - Gripper_R_2
initial:  # Define initial robot poses.
  - group: arm
    pose: Upright
  - group: gripper
    pose: Open